version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "appsync-ohq"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xxxxxxxxxxxxxxxxx"
s3_prefix = "appsync-ohq"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "NeptuneClusterReadOnlyEndpoint=\"https://mydatabase.com:8182/gremlin\" VPCSubnetsPrivate=\"subnet-xxxxxxxxxxxxxxxxx,subnet-xxxxxxxxxxxxxxxxx,subnet-xxxxxxxxxxxxxxxxx\" VPCSecretsManagerSG=\"sg-xxxxxxxxxxxxxxxxx\""